#!/usr/bin/env node
// Generates the tool reference from the live tool definitions so docs never drift.
//   node scripts/gen-docs.js          write docs/TOOLS.md and skills/computer-skills/references/tools.md
//   node scripts/gen-docs.js --check  exit 1 if they are out of date
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL_TOOLS } from '../src/tools/index.js';
import { CHECK_TYPES } from '../src/verify/checks.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const targets = [path.join(root, 'docs', 'TOOLS.md'), path.join(root, 'skills', 'computer-skills', 'references', 'tools.md')];

function typeOf(s) {
  if (!s) return 'any';
  if (s.anyOf) return s.anyOf.map(typeOf).join(' \\| ');
  if (s.enum) return s.enum.map((e) => `\`${e}\``).join(', ');
  if (s.type === 'array') return `${typeOf(s.items)}[]`;
  return Array.isArray(s.type) ? s.type.join(' \\| ') : s.type ?? 'object';
}

export function render() {
  const out = [];
  out.push('# Tool reference', '');
  out.push('<!-- Generated by scripts/gen-docs.js from src/tools — do not edit by hand. -->', '');
  out.push('Every non-read-only tool also accepts `confirm` (a single-use approval token returned by a `CONFIRMATION_REQUIRED` error; only valid after the user approved that exact action).', '');
  out.push('Errors are returned as `{"error": {"code", "message", "hint", "recoverable", "details"}}` with codes: `INVALID_ARGUMENT`, `NOT_FOUND`, `TIMEOUT`, `PERMISSION_DENIED`, `POLICY_DENIED`, `CONFIRMATION_REQUIRED`, `KILL_SWITCH`, `UNSUPPORTED`, `DEPENDENCY_MISSING`, `BACKEND_FAILED`, `APP_NOT_RUNNING`, `VERIFICATION_FAILED`, `CANCELLED`, `INTERNAL`.', '');
  out.push('| Tool | Purpose | Read-only |', '|---|---|---|');
  for (const t of ALL_TOOLS) out.push(`| [\`${t.name}\`](#${t.name}) | ${t.title} | ${t.readOnly ? 'yes' : 'no'} |`);
  out.push('');
  for (const t of ALL_TOOLS) {
    out.push(`## ${t.name}`, '', `**${t.title}.** ${t.description}`, '');
    const props = Object.entries(t.inputSchema.properties || {});
    if (props.length) {
      out.push('| Parameter | Type | Required | Description |', '|---|---|---|---|');
      const req = new Set(t.inputSchema.required || []);
      for (const [k, s] of props) out.push(`| \`${k}\` | ${typeOf(s)} | ${req.has(k) ? 'yes' : ''} | ${(s.description || '').replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`);
      out.push('');
    }
  }
  out.push('## Verification checks', '', 'Used by `verify`, workflow step `expect`, `preconditions` and `expected_results`.', '');
  out.push('| Type | Meaning |', '|---|---|');
  for (const [k, v] of Object.entries(CHECK_TYPES)) out.push(`| \`${k}\` | ${v} |`);
  out.push('', 'Window-related checks accept `window_id`, `title` (fuzzy), `title_regex`, `app`, `pid`. Any check accepts a `label` echoed back in results.', '');
  return out.join('\n');
}

const check = process.argv.includes('--check');
const text = render();
let stale = false;
for (const f of targets) {
  const cur = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : '';
  if (cur !== text) {
    stale = true;
    if (!check) {
      fs.mkdirSync(path.dirname(f), { recursive: true });
      fs.writeFileSync(f, text);
      console.log(`wrote ${path.relative(root, f)}`);
    }
  }
}
if (check && stale) {
  console.error('Tool docs are out of date: run `node scripts/gen-docs.js`.');
  process.exit(1);
}
